### ISSUE TITLE
Binary sensor motion alarm not created

### ISSUE THREAD

**Issue by DR00ME** [user2684/imou_life#103]
Hello,

I have tried to load the integration a few times but it wont create this binary sensor "motion alarm"
IT does create the other binary sensor called "online"
 
Camera is IPC-G26E (imou bullet)

I got your latest release installed.
HA Core: 2024.3.1

TIA

**Comment by user2684** [comment]
Hi, can you please share the logs as per https://github.com/user2684/imou_life?tab=readme-ov-file#troubleshooting?
Thanks

**Comment by DR00ME** [comment]
Here is the diagnostic file information

``
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.3.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Helsinki",
    "os_name": "Linux",
    "os_version": "6.1.73-haos-raspi",
    "supervisor": "2024.03.0",
    "host_os": "Home Assistant OS 12.1",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "nordpool": {
      "version": "0.0.14",
      "requirements": [
        "nordpool>=0.2",
        "backoff"
      ]
    },
    "extended_openai_conversation": {
      "version": "1.0.3",
      "requirements": [
        "openai~=1.3.8"
      ]
    },
    "deebot": {
      "version": "3.2.1",
      "requirements": [
        "deebot-client==5.1.0",
        "numpy>=1.23.2"
      ]
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "imou_life": {
      "version": "1.0.15",
      "requirements": [
        "imouapi==1.0.15"
      ]
    },
    "alexa_media": {
      "version": "4.9.2",
      "requirements": [
        "alexapy==1.27.10",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "imou_life",
    "name": "Imou Life",
    "codeowners": [
      "@user2684"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/user2684/imou_life",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/user2684/imou_life/issues",
    "requirements": [
      "imouapi==1.0.15"
    ],
    "version": "1.0.15",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "**REDACTED**",
      "version": 3,
      "minor_version": 1,
      "domain": "imou_life",
      "title": "Autotalli",
      "data": {
        "api_url": "https://openapi.easy4ip.com/openapi",
        "device_name": "Autotalli",
        "app_id": "**REDACTED**",
        "app_secret": "**REDACTED**",
        "device_id": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "device_info": {
      "api": {
        "base_url": "https://openapi.easy4ip.com/openapi",
        "timeout": 10,
        "is_connected": true
      },
      "device": {
        "device_id": "**REDACTED**",
        "name": "Autotalli",
        "catalog": "IPC",
        "given_name": "Autotalli",
        "model": "IPC-G26E",
        "firmware": "Eng_P_V2.680.0000000.28.R.20210911",
        "manufacturer": "Imou",
        "status": "1",
        "sleepable": false
      },
      "capabilities": [
        {
          "name": "WLAN",
          "description": "Support access to wireless local area network (WLAN)"
        },
        {
          "name": "Auth",
          "description": "Device end loopback RTSP requires authentication (Auth)"
        },
        {
          "name": "DHP2P",
          "description": "Support Dahua P2P Service (DHP2P)"
        },
        {
          "name": "HSEncrypt",
          "description": "Support Huashi WeChat Stream Encryption (HSEncrypt)"
        },
        {
          "name": "BreathingLight",
          "description": "The device has a breathing light (indicator light) (BreathingLight)"
        },
        {
          "name": "CloudStorage",
          "description": "Support for cloud storage of China Vision WeChat platform (CloudStorage)"
        },
        {
          "name": "LocalStorage",
          "description": "Support device local storage, such as SD card or hard disk (LocalStorage)"
        },
        {
          "name": "PlaybackByFilename",
          "description": "The device supports playback based on the file name (PlaybackByFilename)"
        },
        {
          "name": "MT",
          "description": "Support streaming media forwarding capability (MT)"
        },
        {
          "name": "CK",
          "description": "The device supports CustomKey (CustomKey) (CK)"
        },
        {
          "name": "RD",
          "description": "The device has remote debugging capabilities and supports log extraction (RemoteDebug) (RD)"
        },
        {
          "name": "RDV2",
          "description": "Support RD capability, support data burying point control, support debugging log upload (RDV2)"
        },
        {
          "name": "LocalRecord",
          "description": "Support device local recording settings (LocalRecord)"
        },
        {
          "name": "XUpgrade",
          "description": "Cloud Upgrade (XUpgrade)"
        },
        {
          "name": "TimeSync",
          "description": "Device supports time synchronization (TimeSync)"
        },
        {
          "name": "ModifyPassword",
          "description": "Support user name password information verification and password modification (ModifyPassword)"
        },
        {
          "name": "LocalStorageEnable",
          "description": "Support device local storage enable switch (LocalStorageEnable)"
        },
        {
          "name": "Siren",
          "description": "Siren (Siren)"
        },
        {
          "name": "WhiteLight",
          "description": "White Light (WhiteLight)"
        },
        {
          "name": "RTSV2",
          "description": "Real-time streaming supports private protocol streaming, supports dynamic port modification (RTSV2)"
        },
        {
          "name": "PBSV2",
          "description": "The playback stream supports private protocol streaming and supports dynamic port modification (PBSV2)"
        },
        {
          "name": "ESV1",
          "description": "Support 0x95 extension header encryption (ESV1)"
        },
        {
          "name": "DaySummerTime",
          "description": "The device supports daily summer time (DaySummerTime)"
        },
        {
          "name": "WeekSummerTime",
          "description": "The device supports weekly daylight saving time (WeekSummerTime)"
        },
        {
          "name": "TAP",
          "description": "Time supports 12-hour and 24-hour switching (TAP)"
        },
        {
          "name": "TimeFormat",
          "description": "Support time format setting (TimeFormat)"
        },
        {
          "name": "PlaySound",
          "description": "Device sound switch capability (PlaySound)"
        },
        {
          "name": "LinkDevAlarm",
          "description": "Associated Device Alarm (LinkDevAlarm)"
        },
        {
          "name": "InfraredLight",
          "description": "Infrared Light (InfraredLight)"
        },
        {
          "name": "SCCode",
          "description": "The device supports SC security code (SCCode)"
        },
        {
          "name": "TimingGraphics",
          "description": "Support the device to capture multiple pictures (TimingGraphics)"
        },
        {
          "name": "DevReset",
          "description": "Device Reset (DevReset)"
        },
        {
          "name": "TLSEnable",
          "description": "Support TLS transmission (TLSEnable)"
        },
        {
          "name": "DHCP",
          "description": "DHCP"
        },
        {
          "name": "ONLDLS",
          "description": "ONLDLS"
        },
        {
          "name": "Reboot",
          "description": "The device supports restarting (Reboot)"
        },
        {
          "name": "NEC",
          "description": "The device supports No encrypt capture (NEC)"
        },
        {
          "name": "CCD",
          "description": "CCD"
        },
        {
          "name": "ME",
          "description": "Support Message Engine (ME)"
        },
        {
          "name": "LRRF",
          "description": "Local recording supports fast forward LocalRecordReplayForward (LRRF)"
        },
        {
          "name": "CDD-OSS",
          "description": "CDD-OSS"
        },
        {
          "name": "CDD-OBS",
          "description": "CDD-OBS"
        },
        {
          "name": "CDD-US3",
          "description": "CDD-US3"
        },
        {
          "name": "CDD-BOS",
          "description": "CDD-BOS"
        },
        {
          "name": "CDD-COS",
          "description": "CDD-COS"
        },
        {
          "name": "CDDV2",
          "description": "CDDV2"
        },
        {
          "name": "CDD",
          "description": "CDD"
        },
        {
          "name": "RemoteControl",
          "description": "Support remote linkage (RemoteControl)"
        },
        {
          "name": "FrameReverse",
          "description": "Support screen flip (FrameReverse)"
        },
        {
          "name": "AudioEncodeControlV2",
          "description": "Supports audio encoding control (on or off), only affects real-time video, video audio, and does not affect intercom audio control (AudioEncodeControlV2)"
        },
        {
          "name": "MDW",
          "description": "motion-detect-window supports motion detection window settings (MDW)"
        },
        {
          "name": "MDS",
          "description": "motion-detect-sensitive supports motion detection sensitivity setting (MDS)"
        },
        {
          "name": "MobileDetect",
          "description": "Mobile Detection (Merged with PIR) (MobileDetect)"
        },
        {
          "name": "SDLIFE",
          "description": "SD card life (SDLIFE)"
        },
        {
          "name": "OSD",
          "description": "Support video channel OSD configuration (OSD)"
        },
        {
          "name": "1080P",
          "description": "Maximum capability set supported by the device (1080P)"
        },
        {
          "name": "mp4",
          "description": "mp4"
        },
        {
          "name": "MDMD",
          "description": "MDMD"
        },
        {
          "name": "VC",
          "description": "VC"
        },
        {
          "name": "WDRV2",
          "description": "Wide dynamic v2, support 0-100 gear configuration (WDRV2)"
        },
        {
          "name": "WLTM",
          "description": "WLTM"
        },
        {
          "name": "VQS",
          "description": "VQS"
        },
        {
          "name": "AudioTalk",
          "description": "Support voice intercom (AudioTalk)"
        },
        {
          "name": "AlarmSound",
          "description": "Support alarm sound setting (AlarmSound)"
        },
        {
          "name": "MotionDetect",
          "description": "Motion detection (MotionDetect)"
        },
        {
          "name": "pushNotifications",
          "description": "Push notifications (pushNotifications)"
        }
      ],
      "switches": [
        {
          "name": "localRecord",
          "description": "Local recording (localRecord)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "motionDetect",
          "description": "Motion detection (motionDetect)",
          "state": true,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "breathingLight",
          "description": "Status indicator (breathingLight)",
          "state": null,
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "audioEncodeControl",
          "description": "Record audio (audioEncodeControl)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "localStorageEnable",
          "description": "Local storage (localStorageEnable)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "whiteLight",
          "description": "White Light (whiteLight)",
          "state": false,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "infraredLight",
          "description": "Infrared light (infraredLight)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "mobileDetect",
          "description": "Mobile detection (mobileDetect)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "tlsEnable",
          "description": "Tls enable (tlsEnable)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "linkDevAlarm",
          "description": "Siren Armed (linkDevAlarm)",
          "state": false,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "playSound",
          "description": "Device sound (playSound)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "pushNotifications",
          "description": "Push notifications (pushNotifications)",
          "state": false,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        }
      ],
      "sensors": [
        {
          "name": "storageUsed",
          "description": "Storage used (storageUsed)",
          "state": 0,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "callbackUrl",
          "description": "Callback url (callbackUrl)",
          "state": "",
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "status",
          "description": "Status (status)",
          "state": "Online",
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        }
      ],
      "binary_sensors": [
        {
          "name": "online",
          "description": "Online (online)",
          "state": true,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        }
      ],
      "selects": [],
      "buttons": [
        {
          "name": "restartDevice",
          "description": "Restart device (restartDevice)",
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "refreshData",
          "description": "Refresh all data (refreshData)",
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "refreshAlarm",
          "description": "Refresh alarm (refreshAlarm)",
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        }
      ],
      "sirens": [
        {
          "name": "siren",
          "description": "Activate siren (siren)",
          "state": false,
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        }
      ],
      "cameras": [
        {
          "name": "camera",
          "description": "Camera (HD) (camera)",
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "cameraSD",
          "description": "Camera (SD) (cameraSD)",
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        }
      ]
    }
  }
}``

**Comment by DR00ME** [comment]
this was diagnostics file information

**Comment by DR00ME** [comment]
[home-assistant_imou_life_2024-03-23T14-27-34.799Z.log](https://github.com/user2684/imou_life/files/14731983/home-assistant_imou_life_2024-03-23T14-27-34.799Z.log)

here is the debug log

**Comment by user2684** [comment]
Hi, thanks. I see a bunch of errors there indeed. Couple of questions first:
- Is the device shared from another account
- Have you hit the API usage limit? (see https://github.com/user2684/imou_life/wiki/Imou-API-usage-restrictions)

Generally speaking, sensors show up based on the model capabilities (you need to enable debug logging to see the full list). Also newer models do use APIs not publicly documented so you may miss some sensors unfortunately.

**Comment by fabryhw** [comment]
Hi,
have the same problem with Imou Cell 2 (IPC-B46L) hope the attached log can help.

[config_entry-imou_life-d0e8ef2fc3de37b9b106a74950b59f97.json](https://github.com/user2684/imou_life/files/15164636/config_entry-imou_life-d0e8ef2fc3de37b9b106a74950b59f97.json)

Integration part start around line 1083

[home-assistant_imou_life_2024-04-30T13-13-17.559Z.log](https://github.com/user2684/imou_life/files/15164645/home-assistant_imou_life_2024-04-30T13-13-17.559Z.log)


Many thanks

**Comment by user2684** [comment]
@fabryhw thanks. Wonder if those errors are related to https://github.com/user2684/imou_life/wiki/Imou-API-usage-restrictions since I see a bunch of lines in the logs which seems related. Thanks

**Comment by johnnylocktang** [comment]
Same here, no limitations and went with Option 3 in Motion Detection Configuration. Been trying to remove / re-add the device.

IPC-B32-V2
by Imou
Firmware: 2.800.0000000.10.R.240131
Hardware: 9L02ECFPDP2DE8E

**Comment by user2684** [comment]
Added to https://github.com/user2684/imou_life/wiki/Known-Issues

**Comment by DR00ME** [comment]
I would like to add that this problem is not related to hitting the API usage limit.

**Comment by user2684** [comment]
Hi @DR00ME got it, I was referring to the "Motion sensor not showing up" known issue since happening in a couple of devices, which I still cannot explain. Thanks
