### ISSUE TITLE
Motion sensor (Motion Alarm) not responding

### ISSUE THREAD

**Issue by tobiradi** [user2684/imou_life#106]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.4.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.73-haos-raspi",
    "supervisor": "2024.04.0",
    "host_os": "Home Assistant OS 12.2",
    "docker_version": "25.0.5",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "landroid_cloud": {
      "version": "5.0.2",
      "requirements": [
        "pyworxcloud==4.1.13"
      ]
    },
    "mass": {
      "version": "2024.3.6",
      "requirements": [
        "music-assistant==2.0.0b131"
      ]
    },
    "ical": {
      "version": "1.6.7",
      "requirements": [
        "icalendar==5.0.7"
      ]
    },
    "iphonedetect": {
      "version": "1.4.0",
      "requirements": []
    },
    "reversotts": {
      "version": "1.0.2",
      "requirements": [
        "pyttsreverso==0.4"
      ]
    },
    "homematicip_local": {
      "version": "1.59.0",
      "requirements": [
        "hahomematic==2024.4.6"
      ]
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "imou_life": {
      "version": "1.0.15",
      "requirements": [
        "imouapi==1.0.15"
      ]
    }
  },
  "integration_manifest": {
    "domain": "imou_life",
    "name": "Imou Life",
    "codeowners": [
      "@user2684"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/user2684/imou_life",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/user2684/imou_life/issues",
    "requirements": [
      "imouapi==1.0.15"
    ],
    "version": "1.0.15",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "**REDACTED**",
      "version": 3,
      "minor_version": 1,
      "domain": "imou_life",
      "title": "Garten",
      "data": {
        "api_url": "https://openapi.easy4ip.com/openapi",
        "device_name": "Garten",
        "app_id": "**REDACTED**",
        "app_secret": "**REDACTED**",
        "device_id": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "device_info": {
      "api": {
        "base_url": "https://openapi.easy4ip.com/openapi",
        "timeout": 10,
        "is_connected": true
      },
      "device": {
        "device_id": "**REDACTED**",
        "name": "Garten",
        "catalog": "IPC-S7C-3M0WE",
        "given_name": "Garten",
        "model": "IPC-S7C-3M0WE",
        "firmware": "2.800.0000000.20.R.240311",
        "manufacturer": "Imou",
        "status": "1",
        "sleepable": false
      },
      "capabilities": [
        {
          "name": "CollectionPoint",
          "description": "Support collection points (CollectionPoint)"
        },
        {
          "name": "other",
          "description": "other"
        },
        {
          "name": "NVM",
          "description": "Night Vision Mode (NVM)"
        },
        {
          "name": "AlarmMD",
          "description": "Support motion detection alarm (AlarmMD)"
        },
        {
          "name": "PT",
          "description": "Support PTZ operation (PT)"
        },
        {
          "name": "WideDynamic",
          "description": "Wide Dynamic (WideDynamic)"
        },
        {
          "name": "PlaySound",
          "description": "Device sound switch capability (PlaySound)"
        },
        {
          "name": "RTSV1",
          "description": "Real-time streaming supports private protocol to pull streaming (RTSV1)"
        },
        {
          "name": "RTSV2",
          "description": "Real-time streaming supports private protocol streaming, supports dynamic port modification (RTSV2)"
        },
        {
          "name": "AiHuman",
          "description": "Humanoid Intelligence (AiHuman)"
        },
        {
          "name": "LinkDevAlarm",
          "description": "Associated Device Alarm (LinkDevAlarm)"
        },
        {
          "name": "ChnLocalStorage",
          "description": "Support channel local storage, such as SD card or hard disk (ChnLocalStorage)"
        },
        {
          "name": "CloudStorage",
          "description": "Support for cloud storage of China Vision WeChat platform (CloudStorage)"
        },
        {
          "name": "BreathingLight",
          "description": "The device has a breathing light (indicator light) (BreathingLight)"
        },
        {
          "name": "ChnSiren",
          "description": "ChnSiren"
        },
        {
          "name": "LocalStorageEnable",
          "description": "Support device local storage enable switch (LocalStorageEnable)"
        },
        {
          "name": "LocalStorage",
          "description": "Support device local storage, such as SD card or hard disk (LocalStorage)"
        },
        {
          "name": "TLSEnable",
          "description": "Support TLS transmission (TLSEnable)"
        },
        {
          "name": "PTZ",
          "description": "Support PTZ and digital zoom operation (PTZ)"
        },
        {
          "name": "AudioEncodeControlV2",
          "description": "Supports audio encoding control (on or off), only affects real-time video, video audio, and does not affect intercom audio control (AudioEncodeControlV2)"
        },
        {
          "name": "PTZS",
          "description": "PTZS"
        },
        {
          "name": "CRMD",
          "description": "CRMD"
        },
        {
          "name": "LRRF",
          "description": "Local recording supports fast forward LocalRecordReplayForward (LRRF)"
        },
        {
          "name": "WLM",
          "description": "WLM"
        },
        {
          "name": "CRMDR",
          "description": "CRMDR"
        },
        {
          "name": "WLV3",
          "description": "WLV3"
        },
        {
          "name": "HeaderDetect",
          "description": "Support head detection (HeaderDetect)"
        },
        {
          "name": "MDS",
          "description": "motion-detect-sensitive supports motion detection sensitivity setting (MDS)"
        },
        {
          "name": "TimeFormat",
          "description": "Support time format setting (TimeFormat)"
        },
        {
          "name": "OSD",
          "description": "Support video channel OSD configuration (OSD)"
        },
        {
          "name": "AlarmPIRV2",
          "description": "With PIR capability, with PIR enable switch, without PIR detection area setting (AlarmPIRV2)"
        },
        {
          "name": "LinkageSiren",
          "description": "Alarm Linkage Siren (LinkageSiren)"
        },
        {
          "name": "AlarmPIRV3",
          "description": "PIR capability, PIR enable switch, PIR detection area setting (AlarmPIRV3)"
        },
        {
          "name": "AlarmPIR",
          "description": "With PIR capability, without PIR enable switch, without PIR detection area setting (AlarmPIR)"
        },
        {
          "name": "SLAlarm",
          "description": "The device supports sound and light alarm (sound and light alarm) (SLAlarm)"
        },
        {
          "name": "RQD",
          "description": "RQD"
        },
        {
          "name": "Siren",
          "description": "Siren (Siren)"
        },
        {
          "name": "WhiteLight",
          "description": "White Light (WhiteLight)"
        },
        {
          "name": "FrameReverse",
          "description": "Support screen flip (FrameReverse)"
        },
        {
          "name": "CRMDSENS",
          "description": "CRMDSENS"
        },
        {
          "name": "AudioTalk",
          "description": "Support voice intercom (AudioTalk)"
        },
        {
          "name": "LEDS",
          "description": "Fill light sensitivity (LEDS)"
        },
        {
          "name": "PT1",
          "description": "Ranger2 only supports 4-way pan/tilt capability. Does not support zoom in and out Does not supportdigital zoom operation (PT1)"
        },
        {
          "name": "VC",
          "description": "VC"
        },
        {
          "name": "LocalRecord",
          "description": "Support device local recording settings (LocalRecord)"
        },
        {
          "name": "Reboot",
          "description": "The device supports restarting (Reboot)"
        },
        {
          "name": "MobileDetect",
          "description": "Mobile Detection (Merged with PIR) (MobileDetect)"
        },
        {
          "name": "AudioTalkV1",
          "description": "Support voice intercom (AudioTalkV1)"
        },
        {
          "name": "SmartTrack",
          "description": "Support Smart Tracking (SmartTrack)"
        },
        {
          "name": "TimingGraphics",
          "description": "Support the device to capture multiple pictures (TimingGraphics)"
        },
        {
          "name": "ChnWhiteLight",
          "description": "ChnWhiteLight"
        },
        {
          "name": "CRC",
          "description": "CRC"
        },
        {
          "name": "CheckBox",
          "description": "CheckBox"
        },
        {
          "name": "CRH",
          "description": "CRH"
        },
        {
          "name": "PBSV1",
          "description": "Playback stream supports private protocol to pull stream (PBSV1)"
        },
        {
          "name": "PBSV2",
          "description": "The playback stream supports private protocol streaming and supports dynamic port modification (PBSV2)"
        },
        {
          "name": "TSV2",
          "description": "Voice intercom streaming supports private protocol streaming, supports dynamic port modification (TSV2)"
        },
        {
          "name": "TSV1",
          "description": "Voice intercom streaming supports private protocol to pull streaming (TSV1)"
        },
        {
          "name": "PlaybackByFilename",
          "description": "The device supports playback based on the file name (PlaybackByFilename)"
        },
        {
          "name": "PTZ1",
          "description": "PTZ1"
        },
        {
          "name": "TCM",
          "description": "Support Three code megre (TCM)"
        },
        {
          "name": "UOIF",
          "description": "UOIF"
        },
        {
          "name": "MotionDetect",
          "description": "Motion detection (MotionDetect)"
        },
        {
          "name": "Linkagewhitelight",
          "description": "Alarm white light (Linkagewhitelight)"
        }
      ],
      "switches": [
        {
          "name": "localRecord",
          "description": "Local recording (localRecord)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "motionDetect",
          "description": "Motion detection (motionDetect)",
          "state": false,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "breathingLight",
          "description": "Status indicator (breathingLight)",
          "state": true,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "smartTrack",
          "description": "Smart Tracking (smartTrack)",
          "state": true,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "headerDetect",
          "description": "Human detection (headerDetect)",
          "state": false,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "alarmPIR",
          "description": "PIR alarm (alarmPIR)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "audioEncodeControl",
          "description": "Record audio (audioEncodeControl)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "localStorageEnable",
          "description": "Local storage (localStorageEnable)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "whiteLight",
          "description": "White Light (whiteLight)",
          "state": false,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "linkageWhiteLight",
          "description": "White light armed (linkageWhiteLight)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "linkageSiren",
          "description": "Siren Armed (linkageSiren)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "mobileDetect",
          "description": "Mobile detection (mobileDetect)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "tlsEnable",
          "description": "Tls enable (tlsEnable)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "aiHuman",
          "description": "Humanoid AI (aiHuman)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "linkDevAlarm",
          "description": "Siren Armed (linkDevAlarm)",
          "state": false,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "playSound",
          "description": "Device sound (playSound)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "wideDynamic",
          "description": "HDR (wideDynamic)",
          "state": null,
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        }
      ],
      "sensors": [
        {
          "name": "storageUsed",
          "description": "Storage used (storageUsed)",
          "state": 0,
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "callbackUrl",
          "description": "Callback url (callbackUrl)",
          "state": "",
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        },
        {
          "name": "status",
          "description": "Status (status)",
          "state": "Online",
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        }
      ],
      "binary_sensors": [
        {
          "name": "motionAlarm",
          "description": "Motion Alarm (motionAlarm)",
          "state": null,
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        }
      ],
      "selects": [
        {
          "name": "nightVisionMode",
          "description": "Night vision mode (nightVisionMode)",
          "current_option": "Intelligent",
          "available_options": [
            "Intelligent",
            "FullColor",
            "Infrared",
            "Off"
          ],
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        }
      ],
      "buttons": [
        {
          "name": "restartDevice",
          "description": "Restart device (restartDevice)",
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "refreshData",
          "description": "Refresh all data (refreshData)",
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "refreshAlarm",
          "description": "Refresh alarm (refreshAlarm)",
          "is_enabled": true,
          "is_updated": true,
          "attributes": {}
        }
      ],
      "sirens": [
        {
          "name": "siren",
          "description": "Activate siren (siren)",
          "state": false,
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        }
      ],
      "cameras": [
        {
          "name": "camera",
          "description": "Camera (HD) (camera)",
          "is_enabled": true,
          "is_updated": false,
          "attributes": {}
        },
        {
          "name": "cameraSD",
          "description": "Camera (SD) (cameraSD)",
          "is_enabled": false,
          "is_updated": false,
          "attributes": {}
        }
      ]
    }
  }
}
![Screenshot (98)](https://github.com/user2684/imou_life/assets/74401297/71decc45-2a2e-4bf8-9e4c-a2a8f86ea115)

**Comment by user2684** [comment]
Hi, looks like this model is not fully supported or at least using a different format for the messages. Is it a IPC-S7C-3M0WE? Is it just the motion alarm not working or also the other entities? Thanks

**Comment by tobiradi** [comment]
yes, it is the model mentioned. The detection sensors don't work and various others don't work either.

**Comment by user2684** [comment]
Thanks, let me added to the queue in a blocked status, waiting to discover the APIs in more details. I've also added a note here: https://github.com/user2684/imou_life/wiki/Supported-models

**Comment by PawelDino** [comment]
I contacted with IMOU and I received information that this camera (Crusier 2 and also Rex 3D) are treated as not camera but as IOT device. So if you want to recieve push notification from IMOU servers you need register such callback. I do that and I recived push.

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
