### ISSUE TITLE
Cruiser Dual second Videofeed

### ISSUE THREAD

**Issue by mute2014** [user2684/imou_life#109]
Hi there

My Cruiser Dual works perfectly with 1 Videostream/Cam.
As the name already indicates, does the Cruiser have 2 Lens and Videostreams. 1 Fixed and 1 moving lense.
Is it possible to support this Model with a second Videostream and its features (Motion Sensors, Light, etc.)

Perhaps its possible to use both cameras as 2 seperate devices. 

https://www.imoulife.com/en/product/detail/cruiser-dual

Great work!

**Comment by user2684** [comment]
Hi unfortunately, not until Imou will publish updated documentation for the APIs for the new models :-/

**Comment by kkmaslowski** [comment]
I have the same camera and same problem.

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
