### ISSUE TITLE
Bullet 3c support

### ISSUE THREAD

**Issue by Extreme79** [user2684/imou_life#110]
Bullet 3c, not in supported list, is anyway found and partially works. I can reboot, I can turn on/off status led, seems I can set illumination type.. But no video in stream entities, no changes in motion detection sensor (probably because push notification switch is not visible) and so on. 
Onvif streams entities works. Onvif motion sensors not. 

**Describe the solution you'd like**
Full support for Bullet 3C ❤️

**Describe alternatives you've considered**
Onvif integration: For video streams it's ok, but it lacks of camera controls and working motion entities

**Comment by user2684** [comment]
Hi, adding to the roadmap but have a look here https://github.com/user2684/imou_life/wiki/I-would-like-to-have-support-for-this-new-model why it would be very long term :-/ Thanks

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
