### ISSUE TITLE
No video view of the Imou Cam

### ISSUE THREAD

**Issue by filippo5589** [user2684/imou_life#111]
@user2684 Hi ,  I installed integration and I followed the guide for the Imou site, everything went well I see all the sensors the camera controls, but the problem is that I don't see the vision of the camera, I don't even have error logs and I don't understand why, I have other cameras from other brands and they work properly.

I am attaching the photo of the only error I see since there are no logs.

Thank you and I hope it can be solved

![IMG_0031](https://github.com/user-attachments/assets/ea35ecc0-1311-4e1f-8551-d5c7473c2f82)

**Comment by david141695** [comment]
I have the same problem! Please help!!!

**Comment by user2684** [comment]
Hi, could you please share device diagnostics and enable and share debug logs? Thanks
https://github.com/user2684/imou_life?tab=readme-ov-file#device-diagnostics

**Comment by user2684** [comment]
Added to https://github.com/user2684/imou_life/wiki/Known-Issues
