### ISSUE TITLE
[Pet detection]

### ISSUE THREAD

**Issue by PaulBiod** [user2684/imou_life#112]
Hi,
The last Imou cams have the ability to detect animal. So, in the app, we can see if the detection is about a human or an animal.
Is there a way to get this information back to HA ?
Thanks

**Comment by user2684** [comment]
Hi, not until these new functionalities will be documented by Imou unfortunately :-( (https://github.com/user2684/imou_life/wiki/I-would-like-to-have-support-for-this-new-model)

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
