### ISSUE TITLE
Insufficient Flow resources

### ISSUE THREAD

**Issue by Diegocampy** [user2684/imou_life#115]
<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

Issues not containing the minimum requirements will be closed:

I have had this integration for a year, apart from sporadic errors in the logs, it has always worked well. For a few days now, it continues to show me this error instead of the video stream. I don't understand why. Do I have to pay imou to manage the camera in the cloud? That's not what I want to do.

## Version of the custom_component 1.0.15

Registratore: homeassistant.components.stream.stream.camera.telecamera_gazebo_camera
Fonte: components/stream/__init__.py:448
Integrazione: Stream (documentazione, problemi)
Prima occorrenza: 14:10:42 (16 occorrenze)
Ultima registrazione: 14:30:55

Errore da stream worker: flusso terminato; nessun pacchetto aggiuntivo

**Comment by user2684** [comment]
Any additional detail or log? thanks

**Comment by Diegocampy** [comment]
I close issue, is not a issue, but a change in api imou. I delete te integration, and I will change my cam.
