### ISSUE TITLE
Requirements for imou_life not found: ['imouapi==1.0.15']

### ISSUE THREAD

**Issue by hernnyy** [user2684/imou_life#116]
Im having this issue in my Imou life integration.

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 8:09:30 PM (1 occurrences)
Last logged: 8:09:30 PM

Setup failed for custom integration 'imou_life': Requirements for imou_life not found: ['imouapi==1.0.15'].

Full log

[home-assistant_2024-09-30T23-15-03.726Z.log](https://github.com/user-attachments/files/17197376/home-assistant_2024-09-30T23-15-03.726Z.log)

![image](https://github.com/user-attachments/assets/643c9b6d-8f24-44a1-b900-dcc53554aa46)

## Version of the custom_component
1.0.15

**Comment by user2684** [comment]
Try installing the library manually with pip install imouapi==1.0.15, it should do it automatically but maybe something went wrong somehow
