### ISSUE TITLE
Implementation to scrypted

### ISSUE THREAD

**Issue by drodmantras** [user2684/imou_life#12]
Would it be possible to integrate your de to scryptedimilar to ring plugin where you log in, get your cameras listed and can add and view them? since you already have it written for homeassistant?
https://github.com/koush/scrypted/tree/main/plugins/ring

**Comment by user2684** [comment]
Hi! Do you mean adding support for Ring Cameras? They look like a completely different model than Imou and seems to be supported by https://www.home-assistant.io/integrations/ring/. Or do you mean adding Imou cameras support for the Scrypted platform? Thanks

**Comment by drodmantras** [comment]
I meant adding the support for imou life cameras to the scrypted platform. Same as homeassistant where you log in and get list and can add them etc. but i shared ring just for reference

**Comment by drodmantras** [comment]
Since some devices have to be woken up by cloud connection (db60 for example) and i think with your code it could be possible to integrate cloud live stream to scrypted

**Comment by user2684** [comment]
Got it. Ok will keep it here as possible future enhancement but I'd wait till this integration will reach a decent point of completeness in terms of features and stability before evaluating the porting to another home automation framework.
Thanks!

**Comment by user2684** [comment]
Closing for now, integrating with another framework would be too complex at this stage
