### ISSUE TITLE
Support for Chinese version of imou camera

### ISSUE THREAD

**Issue by soulripper13** [user2684/imou_life#121]
## Configuration

```yaml
Add your logs here.
```

## Describe the bug
I tried adding Chinese version of imou camera model K2D but was unsuccessful. I get API error. Is there a specific API url for Chinese versions?

## Debug log

```text

Add your logs here.

```

**Comment by user2684** [comment]
If it is a new model, it makes sense unfortunately. Have  a look at [this](https://github.com/user2684/imou_life/wiki/I-would-like-to-have-support-for-this-new-model)
