### ISSUE TITLE
camera not streaming only in idle condition all Imou cameras

### ISSUE THREAD

**Issue by sushjai** [user2684/imou_life#122]
all other sensors working but camera hd or sd not streaming kindly help me with the solution

**Comment by siewca955** [comment]
Me to

**Comment by dirks67** [comment]
same problem

**Comment by radnek82** [comment]
same to me

**Comment by frankymb** [comment]
same here, camera is black in live, or just broken preview on auto mode

**Comment by letruxux** [comment]
Same here, in the dashboard preview is broken

**Comment by rudikof01** [comment]
I have the same problem, all camera functions available and no streaming.  Does anyone have any suspicions as to why this is so?

**Comment by toloomierz** [comment]
same here  , camera model "cruiser SE+ 3K"

**Comment by basilottac** [comment]
Same here, 2 cameras Cue2 help please. With Onvif works

**Comment by user2684** [comment]
I do recommend to use onvif regardless, since the connection is local and not going through the cloud. 
Also, have a look at [this](https://github.com/user2684/imou_life/wiki/Is-this-an-official-integration%3F)
