### ISSUE TITLE
Change base url for API

### ISSUE THREAD

**Issue by angdolf** [user2684/imou_life#16]
Hi,

Currently the option to configure the base url is only allowed when the integration completes setup. 

Suggest to have an option to input a custom url at the same time when inputting the AppId and AppSecret. This would allow for setup of devices from another region (https://openapi.lechange.cn:443/openapi), without first having devices tagged to "https://openapi.easy4ip.com/openapi". 

Thanks!

<Ref
The following options can be customized through the UI by clicking on the "Configure" link:

Polling interval - how often to refresh the data (in seconds, default 15 minutes)
API Base URL - th url of the Imou Life API (default https://openapi.easy4ip.com/openapi)
API Timeout - API call timeout in seconds (default 10 seconds)
Callback URL - when push notifications are enabled, full url to use as a callback for push notifications
/>

**Comment by user2684** [comment]
Implemented in version 1.0.7
