### ISSUE TITLE
Is it possible to add a favorites feature. For PTZ cameras.

### ISSUE THREAD

**Issue by stylishkrio** [user2684/imou_life#34]
Is it possible to add a favorites feature. For PTZ cameras. PTZ cameras have this function in the original application.

**Comment by user2684** [comment]
I don't see PTZ favorites mentioned in the API documentation (https://open.imoulife.com/book/http/device/operate/controlMovePTZ.html and others). Try having a look if I've missed something. If there isn't maybe it is something stored locally by the Imou Life app :-/

**Comment by user2684** [comment]
Implemented in 1.0.9
