### ISSUE TITLE
Service camera take snapshot error

### ISSUE THREAD

**Issue by phuongnd01904** [user2684/imou_life#40]
I create automation and call service camera take snapshot but it error. I check Trace log it show error in image.
Thank so much!

![image](https://user-images.githubusercontent.com/25190439/205806175-90a2daa2-5c68-448e-8424-ea092d05a11f.png)

**Comment by user2684** [comment]
Thanks. When requesting a snapshot it takes a while for the image to be available so to be picked up. If you run the same command, it may work. Right now I'm waiting for 1 second for the image to be available. I may want to increase this value...

**Comment by user2684** [comment]
This can be now customized in the options, marked as fixed, reopen it in case of problems. Thanks!
