### ISSUE TITLE
iMou Ranger 2 4MP No video feed

### ISSUE THREAD

**Issue by marcinbauer85** [user2684/imou_life#43]
## Version of the custom_component
Lastest 1.0.12

## Describe the bug

Added a new iMou Ranger 2 4MP via Homeassistant HACS integration. All entities like switches, statuses work, but camera feed is broken (no image) on either the "HD" or "SD" channel.

## Hardware
IPC-A42-D
by Imou
Firmware: 2.800.0000000.11.R.220812
Hardware: 8C07422PAZC614A

**Comment by marcinbauer85** [comment]
Just tested, and with ONVIF this camera also doesn't work :( Anyone has ideas why?

**Comment by user2684** [comment]
Hi! strange I think other user are using the same camera with no issue. Could you please go over https://github.com/user2684/imou_life#troubleshooting and provide both diagnostics and debug logs? We should see from there if there is any error or exception coming from the backend. Thanks!

**Comment by marcinbauer85** [comment]
Turns out my camera was faulty. When I exchanged it now it works.
