### ISSUE TITLE
Real Time Alarm update

### ISSUE THREAD

**Issue by mkhalil1991** [user2684/imou_life#49]
Hi There,

I have this configuration but the motion alarm is a bit pointless. Can you please advise on how can I get real-time alarm updates since I will configure my security lights based on the alarm inputs. 

Thanks

**Comment by thewan056** [comment]
Instructions are already on the main page:

https://github.com/user2684/imou_life#option-3

**Comment by user2684** [comment]
Yes, you got the point, if you want a realtime motion sensor you need to enable push notifications, there is no other way to get this with the APIs unless polling continuously (which would hit the limit on Imou side)
