### ISSUE TITLE
Bullet & Cruiser - Mention "IDLE"

### ISSUE THREAD

**Issue by R2d2cpo** [user2684/imou_life#54]
Hi There,

I have 4 imou camera : 

1 x Bullet 2C - 4MP
1 X Cruiser - 4MP
2 X Ranger 2C - 4MP

For the 2 x Rangers the integration works normally.
For the other two models, Cruiser & Bullet, to the right of the window at the bottom, 
I have a mention "inactive" -> "Idle" which is displayed.
The stream does not happen. The image refreshes every 10s.
How to solve this? 

Thanks in advance.
![HA - Imou - Idle](https://user-images.githubusercontent.com/59256243/223494056-63b23cc3-a772-4f0f-bf4e-31217bc5fa70.png)

**Comment by user2684** [comment]
Hi! When there is no stream available, Home Assistant creates a "fake" stream with 10s snapshots. Can you please have a look at the logs if there is any error when you open the stream? If not, please enable debug logging (https://github.com/user2684/imou_life#debugging). Thanks!

**Comment by R2d2cpo** [comment]
Hello, 
I solved the problem by duplicating the views that were doing correctly.
So I had the "Live" option which was present.
Now everything works normally.
