### ISSUE TITLE
Cell Go support?

### ISSUE THREAD

**Issue by erich74** [user2684/imou_life#55]
**Is your feature request related to a problem? Please describe.**
I have integrated an Imou Cell go camera into HA but I can't get any live feed and some sensors are not reported (like Battery reports unavailable)

**Describe the solution you'd like**
I might be totally wrong but I read request #36 and it seems the Cell go is not that much different (battery operated, no permanent live feed)...reason why I am opening it as a request as there's no official support yet I guess 

Thanks
Eric

**Comment by user2684** [comment]
Hi, can you please both diagnostic and debug logs so to have a better look at it? Might be this model does not expose certain capabilities. Thanks!

**Comment by erich74** [comment]
Thanks for your answer, sorry to ask but do you have a link about which exact information you need? I am pretty new to HA, not sure how/where to get the requested diag/debug logs.
Thanks

**Comment by user2684** [comment]
Sure no problem, have a look at this: https://github.com/user2684/imou_life#troubleshooting
Thanks

**Comment by MiAutomations** [comment]
Please let me know if you need any further information or logs in order to try support this device 

Thank you

**Comment by user2684** [comment]
Thanks for the logs. From what I can see, the device is recognized as a "dormant" device correctly but the method we found in #36 by calling the closeDormant function to wake it up, it doesn't work here since not supported (invalid parameter). Unfortunately Imou is not keeping up to date the API specs at https://open.imoulife.com/book/en/start.html and there are no evidence on how to interact with those devices, how to wake them up etc. There is for sure a way because this is what the Imou Life app does but it is not easy to guess like we did in #36 since it is not publicly documented. I'll keep this open and in case I can get such a device for more detailed tests I'll dig into. Meanwhile if anybody identifies the right api to interact with those devices, please let me know.

**Comment by erich74** [comment]
Ok no problem, thanks a lot for your help and for your great work with this imou integration
Eric

**Comment by MiAutomations** [comment]
> Thanks for the logs. From what I can see, the device is recognized as a "dormant" device correctly but the method we found in #36 by calling the closeDormant function to wake it up, it doesn't work here since not supported (invalid parameter). Unfortunately Imou is not keeping up to date the API specs at https://open.imoulife.com/book/en/start.html and there are no evidence on how to interact with those devices, how to wake them up etc. There is for sure a way because this is what the Imou Life app does but it is not easy to guess like we did in #36 since it is not publicly documented. I'll keep this open and in case I can get such a device for more detailed tests I'll dig into. Meanwhile if anybody identifies the right api to interact with those devices, please let me know.

Probably if anyone have access to the new model Imou Cell 2 is a good test also in order to check this parameter

**Comment by user2684** [comment]
agree, it is really try and error and the complexity is also that since looks like Imou is updating their API but not their documentation, sometimes is really difficult to guess what to call. *maybe* one way could be to intercept in the network the calls issued by the camera but the SSL certificate could prevent this. Another could be to ask the Imou support but I never got decent answers from them.

**Comment by tango13** [comment]
I just got a Cell Go camera, which I thought I could manage with Home Assistant through this integration. Instead, this particular model seems to have a lot of problems which, from what I read, don't seem to have the possibility to be solved easily or quickly. Please let me know if I can be of any help, otherwise I believe I might be forced to return the camera. Thank you.

**Comment by giddorah** [comment]
I also have one of these cameras and would gladly do whatever I can to assist in finding a way through its limitations. Ask away :)

**Comment by tango13** [comment]
I've set up Postman and followed some directions as outlined in request #36, so far with some success.
The closeDormant function actually does seem to wake the camera up: if I call it and then go to see the live stream on the app, the camera responds immediately, without the initial delay when it typically wakes up.
I can also get information about the status of the battery.
Still trying some functions at random, but things seem to work as expected.
Please let me know if I should test something specific.
Thank you.

**Comment by user2684** [comment]
Great, thank you. Unfortunately without having the model to test it is very difficult for me to implement something when blind :-) 
First of all we need to understand why when the integration calls the closeDormant api will get not supported (from your logs) while for you it is working fine. Are you calling it with different parameters? Thanks

**Comment by tango13** [comment]
Here's what I am doing with Postman, tried some different functions:

get camera status through the "deviceOnline" call with these parameters
{
 "system": {
    "ver": "1.0", 
    "sign": "{{sign}}",
    "appId": "{{appId}}",
    "time": {{time}}, 
    "nonce": "{{nonce}}"
  },
  "params":{
		"token":"{{accessToken}}", 
		"deviceId":"XXXXXXXXXXXXXXX"
    },
  "id": "{{id}}"
}

I get
{"result":{"msg":"Operation is successful.","code":"0","data":{"productId":"XXXXXXX","channels":[{"channelId":"0","onLine":"4"}],"deviceId":"XXXXXXXXXXX","onLine":"4"}},"id":"7"}

the onLine=4, if I got it correctly, means sleeping, right?

Then I call the wakeUpDevice function with the following parameters

{
    "system":{
        "ver":"1.0",
        "appId":"{{appId}}",
        "sign":"{{sign}}",
        "time":{{time}},
        "nonce":"{{nonce}}"
    },
    "id":"{{id}}",
    "params":{
        "token":"{{accessToken}}",
        "deviceId":"XXXXXXXXXXXXXXXXXXX",
        "url":"/device/wakeup"
    }
}

and I get in response

{"result":{"msg":"Operation is successful.","code":"0"},"id":"39"}

Right after calling the wakeup function, if I send a deviceOnline call I get

{"result":{"msg":"Operation is successful.","code":"0","data":{"productId":"XXXXXXX","channels":[{"channelId":"0","onLine":"1"}],"deviceId":"XXXXXXXXXXXXX","onLine":"1"}},"id":"21"}

the online=1 means online, correct?

Please let me know if you need me to do further testing.

Thank you.

**Comment by user2684** [comment]
Yes, online should mean the device is actually online. Just check maybe that after this message you can get a snapshot, move the switches etc. so to be sure the device is really back online. Thanks!

**Comment by tango13** [comment]
This is the log HA produces about the imou_life custom component:

2023-12-04 16:36:55.187 ERROR (MainThread) [custom_components.imou_life] APIError: OP1003: Invalid parameter (incorrect or null), please modify parameter
Traceback (most recent call last):
  File "/config/custom_components/imou_life/entity.py", line 79, in async_added_to_hass
    await self.sensor_instance.async_update()
  File "/usr/local/lib/python3.11/site-packages/imouapi/device_entity.py", line 285, in async_update
    if not await self._async_is_ready():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/imouapi/device_entity.py", line 86, in _async_is_ready
    awake = await self._device_instance.async_wakeup()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/imouapi/device.py", line 384, in async_wakeup
    await self._api_client.async_api_setDeviceCameraStatus(self._device_id, "closeDormant", True)
  File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 359, in async_api_setDeviceCameraStatus
    return await self._async_call_api(api, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 216, in _async_call_api
    raise APIError(error_message)
imouapi.exceptions.APIError: OP1003: Invalid parameter (incorrect or null), please modify parameter

**Comment by MiAutomations** [comment]
> Good news! After some debugging and analysis, I managed to see the Cell Go device correctly in HA! What I did was to add a "channelId":"0" to the payload in function async_api_setDeviceCameraStatus in file api.py. I know that in the Imou API documentation the channelId parameter is not mandatory but I verified with Postman that without it the API call doesn't work and returns the OP1003 error as per above. I don't know if this change breaks the compatibility with other cameras, but at least for the Cell Go model apparently it is required. Controls and sensors now seem to work as expected, and I also get a live stream through the Camera HD sensor.

Great News!

Can you please let us know if you are able to see the live stream of this camera model over the HA? If Yes can you please give us more details how to perform this? 

Thank you

**Comment by MiAutomations** [comment]
> Yes, I can see the live stream in HA but it's kind of hit or miss, sometimes it works, sometimes not. I am also verifying the battery drain: it seems that after connecting the camera in HA the battery has a much higher discharge rate.

This is great even if for some times works or not ...

Yes its expected that the battery drain more faster once the stream is always active 

Can you please give more information about how to achieve this integration in HA? 

Thank you

**Comment by user2684** [comment]
Excellent job @tango13 !! Just to fully understand the process here: the device is correctly identified as a "dormant" but was not correctly woke up by the integration. If you instead manually call async_api_setDeviceCameraStatus with the channel id, then the device wakes up and you can interact with it, correct? Battery drain is normal and the fact that the imou service with these devices is not always perfect is unfortunately also kind of expected.

Now if what we need is just to make the channel explicit, can be an easy change in the code so if so let me know.
Of course I would also need to check if this would not bring any impact on other camera models but regardless can be an easy fix. 
Let me know.
Thanks!

**Comment by user2684** [comment]
Linking this also with #36

**Comment by user2684** [comment]
Perfect thanks, I will do some tests on other models and report back!

**Comment by user2684** [comment]
Hi, I run a test against two other models that I have here (IPC-C22C-D and IPC-C22F-C) and as expected the channelId addition had no impact and everything works correctly. I will add the fix in the next release, I'll keep you posted. Thanks!

**Comment by tango13** [comment]
Great, thank you!
One thing I noticed is that the device is lacking a "motion detected" sensor, which could be used to trigger an alarm: is it expected?

**Comment by user2684** [comment]
Do you mean the motion detection switch or the motion alarm sensor? The first one should be there regardless of the camera's capabilities, the latter only if the device supports the AlarmMD capability. Thanks

**Comment by tango13** [comment]
I mean the motion alarm sensor. Actually the motion detection switch is there correctly, but the motion alarm sensor is not. As far as I understand though, the device doesn't support it, because if I call a device capability list function I don't see the AlarmMD one in the response. 
Too bad, because such a capability would have been very useful inside Home Assistant.
Thank you!

**Comment by user2684** [comment]
Correct! it shows up only if the device is AlarmMD capable. However, this was more an educated guess from my side. If you are familiar with python you could try installing `pip install imouapi` and run `python -m imouapi.cli --app-id <app_id> --app-secret <app_secret> get_device_raw <device_id>` which should "bruteforce" all the possibile capabilities and switches. Feel free to share the result here (but ensure there are no sensitive information in the output). Thanks!

**Comment by tango13** [comment]
Thank you for the info.
Here's what I get in response to the get_device_raw command:

Capabilities:
WLAN: off
DHP2P: off
MT: off
NetSDK: off
HSEncrypt: off
CloudStorage: off
DPS: off
AGW: off
LocalStorage: off
LocalStorageEnable: off
PlaybackByFilename: off
BreathingLight: off
ShineLight: off
RegCode: off
RD: off
RD: off
FaceCapture: off
CK: off
NMP: off
NMPRC: off
TextPush: off
SLAlarm: off
LocalRecord: off
SR: off
QA: off
AntiAddiction: off
AntiAddictionSet: off
AntiAddictionForbid: off
XUpgrade: off
AGWDisarm: off
REMINDER: off
Auth: off
ModifyPassword: off
TimeSync: off
BRestartFormat: off
Siren: off
LinkageSiren: off
SirenTime: off
WhiteLight: off
WL: off
InfraredLight: off
SearchLight: off
NonAccessoriesAdd: off
CallAbility: off
CA: off
NoVA: off
Dormant: off
RTS: off
PBS: off
TS: off
RTS: off
PBS: off
TS: off
ES: off
CallByRtsp: off
DaySummerTime: off
WeekSummerTime: off
SummerTimeOffset: off
TAP: off
SceneMode: off
SMT: off
TimeFormat: off
DDT: off
ACT: off
SIMCA: off
OpenDoorByFace: off
OpenDoorByTouch: off
Ring: off
CustomRing: off
CustomReply: off
LinkDevAlarm: off
LinkAccDevAlarm: off
AbAlarmSound: off
PlaySound: off
PlaySoundModify: off
DLOCS: off
CheckAbDecible: off
Reboot: off
SCCode: off
RingAlarmSound: off
RAS: off
AccessoryAlarmSound: off
InstantDisAlarm: off
IDAP: off
DeviceAlarmSound: off
AX: off
TimingGraphics: off
Talk: off
ErrReport: off
DevReset: off
TLSEnable: off
TCM: off
NEC: off
ME: off
EWL: off
TSVO: off
TSVS: off
DLS: off
DHPenetrate: off
MesTrans: off
PicTrans: off
DataTrans: off
LRRF: off
LRRB: off
UPNP: off
AH: off
IOTTUNNEL: off
AlarmMD: off
PTZ: off
PT: off
PT1: off
PT2: off
AudioEncodeOff: off
AudioEncodeControl: off
AudioEncodeControl: off
FrameReverse: off
RemoteControl: off
Panorama: off
PanoOrder: off
WideAngle: off
MDW: off
MDS: off
HeaderDetect: off
FaceDetect: off
CollectionPoint: off
TimedCruise: off
SmartLocate: off
SmartTrack: off
NumberStat: off
ManNumDec: off
AlarmPIR: off
AlarmPIR: off
HUBAlarmPIR: off
AlarmPIR: off
AlarmPIR: off
MobileDetect: off
ZoomFocus: off
CloseCamera: off
HoveringAlarm: off
HA: off
HA: off
HA: off
BeOpenedDoor: off
RtFaceDetect: off
RtFaceCompa: off
CloseDormant: off
ElecReport: off
WifiReport: off
HeatMap: off
AiHumanCar: off
AiHuman: off
AiCar: off
WideDynamic: off
WDR: off
TalkSoundModify: off
VideoMotionSMD: off
ChnLocalStorage: off
OSD: off
1080P: off
MSS: off
ChnErrReport: off
CCR: off
CLW: off
CLDA: off
NVM: off
LEDS: off
ELCM: off
RL: off
CCS: off
CCSS: off
SDLIFE: off
PostFaceDetect: off
PostFaceAnalysis: off
OPLOG: off
INTERALARM: off
RUNLOG: off
LEDSW: off
DEVSHA: off
AudioTalk: off
AudioTalk: off
AlarmSound: off
Electric: off
WIFI: off
Linkagewhitelight: off
WLM : off
MotionDetect: off
pushNotifications: off

Switches:
localRecord: off
motionDetect: off
faceCapture: off
speechRecognition: off
breathingLight: off
smartLocate: off
smartTrack: off
localAlarmRecord: off
regularCruise: off
headerDetect: on
numberStat: off
manNumDec: off
alarmPIR: on
autoZoomFocus: off
audioEncodeControl: on
aecv3: on
faceDetect: off
localStorageEnable: on
whiteLight: off
linkageWhiteLight: off
linkageSiren: off
infraredLight: off
searchLight: off
hoveringAlarm: off
beOpenedDoor: off
closeCamera: off
mobileDetect: on
rtFaceDetect: off
rtFaceCompa: off
closeDormant: off
heatMap: off
tlsEnable: on
aiHumanCar: off
aiHuman: off
aiCar: off
openDoorByFace: off
openDoorByTouch: off
linkDevAlarm: off
linkAccDevAlarm: off
abAlarmSound: off
playSound: off
wideDynamic: off
smdHuman: off
smdVehicle: off
instantDisAlarm: off
periodDisAlarm: off
ccss: off
inll: off
ledsw: off
pushNotifications: off

Almost everything seems to be set to off, though... 
Can this be useful to you? Can I help further? I really like this camera, so I am willing to cooperate to get the best of it in HA.
Thank you very much for your great work!

**Comment by user2684** [comment]
Closing this since in v1.0.14 just released the additional parameter with channelId has been added. Thanks!

**Comment by user2684** [comment]
Sorry @tango13 I missed your message. Yeah, not very informative the output of the command as I was afraid of :-(

**Comment by MiAutomations** [comment]
Hello 

I just installed the new update for this integration 

![image](https://github.com/user2684/imou_life/assets/47602733/882708b7-10bd-4f6f-a3f2-b5acb4cb07d2)

But I still not able to access the Live stream for the cell go device... even if I try to "activate" the stream from the IMOU APP

Is there any way to access the live stream for this camera model? 

Thank you

**Comment by user2684** [comment]
Reopening the issue. @tango13 is this new release working for you? I've added the channelId information in the API call. Thanks

**Comment by tango13** [comment]
Yes, the new release works well for me.
Thank you.

**Comment by user2684** [comment]
Thanks guys, So looks like the new version is working indeed but there is a problem with the streaming. Couple of questions:

- Was the streaming working with the previous version of the integration?
- Is the device a shared device from a different Imou account?

Thanks

**Comment by tango13** [comment]
>     * Was the streaming working with the previous version of the integration?

For me, it was the same as now, that is sometimes it works, sometimes (well, I should say most of the times) it does not. When it doesn't work, I get a "Error with media stream contents".
 
>     * Is the device a shared device from a different Imou account?

Not in my case.

Thank you!

**Comment by tango13** [comment]
By the way, is there any chance in your opinion to have the motion alarm sensor supported for this camera?
For me it is the most important feature I would use in HA, so I'm afraid I will be forced to return the camera if such a sensor is not available.
Thanks a lot for your precious work.

**Comment by MiAutomations** [comment]
Hello 

I try several times during the last days with the new integration update and I never get the stream working SD or HD, even if I have Preload camera stream option available or even IF I start the stream with IMOU application in order to try "preload" the stream...

**Comment by MiAutomations** [comment]
Hello to all

I opened a Ticket on the IMOU Cloud related to the stream not available from the cell Imou cameras and now I have to respond about, If some one can please help me in order to get this info to reply I will appreciate 

Imou Technical Support Question
Hello, please provide the specific API name, request parameters and return parameters? 

Thank you

**Comment by tango13** [comment]
Hi,
I'm sorry I can't be of any help, as I have sent the camera back some time ago.

**Comment by user2684** [comment]
Added to https://github.com/user2684/imou_life/wiki/Known-Issues

**Comment by DanielElhadif** [comment]
Hello, I have IMOU Cell go, Installed the integration inHA, all info working, but the camera live not working, its only says "Idle" 
looks like sensor not working, its have a fix?
![image](https://github.com/user-attachments/assets/9b8653cd-4bd9-4c8a-8cc7-e9cc256aaff2)
![image](https://github.com/user-attachments/assets/767be317-03ab-48c8-b7e8-5d92260d16cf)

thank you!
