### ISSUE TITLE
Ability to also get a local RTSP stream from the integration and configure via Home Assistant

### ISSUE THREAD

**Issue by julianjwong** [user2684/imou_life#57]
**Is your feature request related to a problem? Please describe.**
Assuming that the current camera stream is via Imou Cloud, would be great to also derive the appropriate RTSP local stream at the same time as configuring this new integration for a camera. That way there is both a cloud and local streaming option.
Configuring the parameters of the stream would be great too (e.g. CBR vs VBR, resolution, max bitrate, brightness, etc.) as per what https://dahuawiki.com/ConfigTool allows.

**Describe the solution you'd like**
Add a new camera stream based on RTSP local network streaming

**Describe alternatives you've considered**
Separate manual RTSP configuration via the Camera or ONVIF Home Assistant integrations.
Separate configuration using the Dahua Windows PC config toolbox. (https://dahuawiki.com/ConfigTool)

**Additional context**
RTSP streams may require the use of the Dahua config app (but possibly could be done via cloud settings) to configure to H264 protocol as I think Home Assistant doesn't support the default H265 compression protocol.

**Comment by user2684** [comment]
Thanks I think is is a great idea but would require some work, added to the roadmap.
Thanks!

**Comment by robroll** [comment]
Hi. This would be great. I could use it for Frigate integration of my remote camera. Thanks.

**Comment by user2684** [comment]
Closing this for now, since replicating what RTSP and onvif integration are doing could be too complicated
