### ISSUE TITLE
Cannot activate siren in Imou Bullet IPC-G26E

### ISSUE THREAD

**Issue by ethernetpl** [user2684/imou_life#61]
Recently I added a  Imou Bullet IPC-G26E to HomeAssitant via Imou life integration.

Device and entities are available in HA.

I'm able to activate/deactivate white light via whitelight entity or watch video stream.

Unfortunately I cannot enable siren from HA site.

Every attempt ends with an error:
"Failed to call service siren/turn_on. DV1026. The device does not support the call of this function."
![signal-2023-05-14-181158_002](https://github.com/user2684/imou_life/assets/6184248/27f8414a-6ef7-4362-9e76-c2cae7922366)

The device is equipped in siren that can be activated in official IMOU app in menu. 

Please let me know if I can provide more info or do some checks.

**Comment by user2684** [comment]
Thanks, actually the siren switch is an undocumented feature which did work for some models but maybe doesn't for all. As new models come out Imou does not update the docs so it is really difficult what api to call for what. And this is common to many issues. I've created #63 to address them all hope sooner later than later

**Comment by loeffen** [comment]
Is this problem solved ? I also cannot enable siren from HA. 

Getting error message: "Kan service siren/turn_on niet aanroepen. DV1026: The device does not support the call of this function."

Thanks for any response ...

**Comment by user2684** [comment]
Hi, nope. Imou is no more updating the public documentation of their APIs hence no news on this topic. Actually I have a camera with a siren and this method works despite undocumented, but guessing which api other models call is almost impossible :-(

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
