### ISSUE TITLE
Licenses Exceed

### ISSUE THREAD

**Issue by night-gold** [user2684/imou_life#62]
Hello,

I installed your integration to my HA yesterday and everything seemed fine but today it suddenly stopped working and asked for a reboot. 

After the reboot the camera is not seen anymore and I just have a log saying that there are api timeout.

I waited a bit to see if this was Imou life APIs that were down for a few minutes but as it did not go up again I started to worry and tested the phone app, and there I could see that everything is working fine.

After that I headed to the open.imoulife.com console and in device I saw that I had a license Exceed:
![image](https://github.com/user2684/imou_life/assets/18196640/4d8b3a7d-c849-4b73-9a3f-b5dbab462440)

I tried to look at your documentation but did not see any information on a license limit, I'm a bit confused as I did not find a lot of infos on the net on that. I tested to close/open the camera a few times (less than 10) and it was yesterday, any idea what I could do to prevent the license exceed?

**Comment by night-gold** [comment]
Ok so I found out, and it was not really easy that you should never, ever, try to use the camera, open/close state to determine when to do things with home-assistant.

Doing that literaly burns through your API quota and you can do nothing for a few days...

As I'm starting to play with it and did not receive everything I started with playing with that, wich broke a lot of things I have to say. Maybe adding a Warning in the documentation could be a good idea.

**Comment by user2684** [comment]
Closing for now since mostly related to Imou API limits
