### ISSUE TITLE
Find a way to reverse engineer Imou Life API calls

### ISSUE THREAD

**Issue by user2684** [user2684/imou_life#63]
Especially with new models, Imou is adding capabilities and changing existing one without updating the API documentation resulting in difficulties to emulate Imou Life behaviour and functionalities. 
We need to find a way (e.g. a proxy?) to intercept the HTTP calls sent from Imou Life to the Imou API so to emulate the same in our integration
Related issues: #61 #48 #35 #55 #59 #60 #51

**Comment by ryrzy** [comment]
any news here? :)

**Comment by user2684** [comment]
Unfortunately no news. I was looking into running Imou Life in an Android emulator to then capture the outbound traffic but still being the communication protected with SSL would not fully work I guess. If anybody has any idea would be happy to hear it :-)

**Comment by ryrzy** [comment]
what about windows app?

**Comment by user2684** [comment]
I tried going towards this route which seems very promising: https://medium.com/@roy2477/decrypting-android-app-ssl-traffic-c480e2143743 but I got stuck in recompiling the apk (without it, the ssl connection does not go through).
If anybody is willing to give a try...
Thanks

**Comment by user2684** [comment]
Ok, dead end unfortunately, I followed the tutorial above, I got the apk installed but the Imou Life app is complaining, saying "please install the official Imou Life app" and then closes itself, must have some sort of built in self-protection which is preventing to debug it properly. Maybe playing with the network communication and/or blocking this check may work but it becomes really too complicated....

**Comment by ryrzy** [comment]
hmmm maybe you should contact with imou devs... they should update api on their www :)

**Comment by user2684** [comment]
I tried for reporting a bug a while ago but I got an answer completely off topic, I cannot even imagine what I can get if asking something which would require such a complex action to collect material and update a website  :-p

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
