### ISSUE TITLE
Error in log when you open camera streem

### ISSUE THREAD

**Issue by Cippo2019** [user2684/imou_life#64]
Hello
thanks in advance for this great plugin

HA version 6.2
OS version 10.2
platform OVA
Custom version 1.0.13
Cam integrated only 1 IPC-S21FE
all work fine when i click on device , i can see after some second the right and fluent video...
on the same time I see on log (every time) this error

2023-06-16 14:04:54.053 ERROR (MainThread) [frontend.js.latest.202306080] blob:http://IP:8123/b857f0f7-f295-4139-a28e-5446e33e16f9:1:100 Uncaught ReferenceError: t is not defined 

thanks in advance
wbr
Cippo

**Comment by user2684** [comment]
Hi Cippo, this doesn't look like caused by this extension, frontend.js.latest is a HA frontend component. Do you see this generated on specific situations when using this extension? Does it prevent anything to work? Thanks

**Comment by Cippo2019** [comment]
HI :-)
custom is fine. all works.
When you click on the cam to see the video stream (directly from the custom for example) or when you integrate an image into a dashboard and click on the image, the video starts after a few seconds. A moment before starting from that you can see the error and it happens every time.
I also tried on another home assistant installation that I have in a test environment and there is the exact same behavior.
Maybe I did something wrong in integrating the cam?
wbr
Cippo

**Comment by user2684** [comment]
No, I think you did everything right, still if this error is not having an impact on the normal operations, I'd live with it for now, especially because the error is coming from a HA component so would be very difficult to troubleshoot it.
Thanks anyway for reporting it :-)
