### ISSUE TITLE
Firmware Upgrade  // this is not a issue but a question

### ISSUE THREAD

**Issue by Cippo2019** [user2684/imou_life#68]
Hi

sorry , this is not a issue but just a question, to avoid problem (I am quite new on use of that add on and I prefer to ask in advance

Imour released a new firmware.
Are there things to consider before updating firmware or we can procede wiht "relax" ?
:-)

wbr

**Comment by user2684** [comment]
Hi, so far nobody reported issues with firmware upgrade but unfortunately it is difficult to know in advance what to expect and if anything changes. Personally I prefer to run old firmware unless there are new capabilities I desperately need but it is a personal choice ;-)
