### ISSUE TITLE
IPC-S21FE Video stream not showing

### ISSUE THREAD

**Issue by arandax** [user2684/imou_life#70]
## Version of the custom_component

1.0.13

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

I got access to a Cruiser cam by a friend who shared it with me. I correctly setup the addon, I get a list of sensor and an HD video feed which it isn't showing (black screen).

## Debug log

![Immagine 2023-08-06 084432](https://github.com/user2684/imou_life/assets/59771093/ea2078e0-28b5-442f-8b23-fbe76a0e5107)

Add your logs here.

```

**Comment by user2684** [comment]
Hi, just seen this issue after replying in the other one, apologize  :-) Ok so looks like apart from the video all the rest seems to be working. To better troubleshoot the video issue, could you please share the logs? Instructions here: https://github.com/user2684/imou_life#troubleshooting
Thanks!

**Comment by arandax** [comment]
Thank you for your reply!
I didn't noticed that there was an SD stream also as the entity was disabled by default, I just turned it on but I can't verify if it works as webcam is offline now.
Other entities are showing but I can't trigger them as I don't have rights to access them, the webcam is shared from owner's account to mine.

**Comment by arandax** [comment]
Is diagnostic enough?
Just tried SD stream, no luck, same as HD stream. In the imou app I have 3 resolutions, 1080 720 and 480, maybe the device sends 3 streams?

[config_entry-imou_life-998c91e6584d5ca00111096476926822.json (1).txt](https://github.com/user2684/imou_life/files/12316465/config_entry-imou_life-998c91e6584d5ca00111096476926822.json.1.txt)

**Comment by arandax** [comment]
Thanks for the reply.
I know for sure that some commands can't really be operated because I indeed have no rights, the webcam is shared to me from the owner's account and he disabled everything but video stream. In the IMOU app actually is the only thing that I can do, watch the stream. Everything else is grayed out.

**Comment by user2684** [comment]
You're right, maybe this can also be related, it might be that when you share a device the api which is called for the video streaming is different. Ideally if you can get full privileges over the device even if just for running the test, would be best to determine 100% if it is a real limitation or just the sharing thing which is preventing the integration to work correctly. Thanks

**Comment by user2684** [comment]
This is related to #80

**Comment by user2684** [comment]
Added to https://github.com/user2684/imou_life/wiki/Known-Issues
