### ISSUE TITLE
speaker integration

### ISSUE THREAD

**Issue by Brizzo89** [user2684/imou_life#76]
HI,
As you probably already know, many IMOU cameras have a built-in speaker that you can communicate with via the app.
In your opinion, is it feasible/possible in some way to implement a function to be able to send text or audio to be played on the speaker?
It would be very nice to be able to use TTS by playing the text on the camera's speaker.
I'm speaking as a bit of a novice, I'm a programmer too but in the industrial sector, if you need help with this, tell me if I can do something.
For example, I have two IPC-S41FEPs.

**Comment by user2684** [comment]
Hi, interesting idea! However, I cannot see from the API published at https://open.imoulife.com/book/en/start.html anything which would help in this direction, have a look if you have better luck. Unfortunately not all the APIs are published so there is for sure a way to do that but without knowing which API is called and how is pretty impossible to implement :-(

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
