### ISSUE TITLE
Cannot start version 1.0.14 in Home Assistant 2023.9.2

### ISSUE THREAD

**Issue by dado483** [user2684/imou_life#84]
## Version of the custom_component

1.0.14

## Describe the bug

After the update of the component i receive the errors below.
PIP version on my Raspberry PI is 23.3.2 and after manual installation imouapi version is 1.0.14:

**pip --version**
pip 23.3.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)

**pip show imouapi**
Name: imouapi
Version: 1.0.14
Summary: Library for controlling Imou devices by interacting with the Imou Life API.
Home-page: https://github.com/user2684/imouapi
Author: user2684
Author-email: user2684@users.noreply.github.com
License: MIT
Location: /home/pi/.local/lib/python3.11/site-packages
Requires: aiohttp, mkdocs-material-extensions, mypy-extensions, pydocstyle, pyproject-api, snowballstemmer, sqlalchemy

No problems with version 1.0.13. At the moment i rollback to this version.

## Debug log

2024-01-04 14:17:06.528 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package imouapi==1.0.14: ERROR: Cannot install imouapi==1.0.14 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

**Comment by user2684** [comment]
Thanks for reporting it, I did upgrade the dependencies with  1.0.14 and probably I've been a bit too strict. But I cannot see which dependency is causing the problem, maybe pip? Thanks
For my own reference, #83 may be related

**Comment by dado483** [comment]
Hi, yes I thin that https://github.com/user2684/imou_life/issues/83 may be related.
It appears that your software is not detecting the installed packages (pip and imouapi) that already are in the version you require. At the same time, automatic packages update didn't work, I had to manually update both pip and imouapi.

**Comment by user2684** [comment]
Got it thank. I need to run some tests to fully reproduce the issue, meanwhile added to the high priority queue. Thanks

**Comment by user2684** [comment]
Hello all, this has been fixed with 1.0.15 just released, please have a look and let me know if you have any issue.
