### ISSUE TITLE
smart plug

### ISSUE THREAD

**Issue by matteos1** [user2684/imou_life#85]
there is a possibility to add to device this smart plug?
thank you
https://www.imoulife.com/en/product/detail/smart-plug

https://it.aliexpress.com/item/1005005333473656.html?gatewayAdapt=glo2ita

**Comment by user2684** [comment]
Adding to the "blocked" development queue where we are tracking those kind of requests. Unfortunately the Imou api documentation is not up to date so it is almost impossible to support new devices unless somebody would discover which api to call. So far no luck :-(

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
