### ISSUE TITLE
IMOU B5 Bulbs, problem.

### ISSUE THREAD

**Issue by scfrancis** [user2684/imou_life#86]
Good morning,
I cannot integrate B5 LED bulbs (from the IMOU brand).
Do you have a tip?
Thanking you

**Comment by user2684** [comment]
Hi, unfortunately those devices do not have public API we can leverage. In case instead you are able to discover those APIs, let me know and I'll work on it :-) Those are the devices supported so far: https://github.com/user2684/imou_life/wiki/Supported-models

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
