### ISSUE TITLE
Imou  Dual Lens camera 

### ISSUE THREAD

**Issue by MiAutomations** [user2684/imou_life#89]
Hello 

I recently have access to the new IMOU cameras Dual Lens, but when I tested this cameras in this integration I have no access to the live stream or either to a almost sensores information/status

![image](https://github.com/user2684/imou_life/assets/47602733/20baa5e0-031d-4c92-a035-7aa00e1bbf30)

Please let me know if you need any further information from my side in order to try add this new model as supported 

Thank you

**Comment by user2684** [comment]
Him, is the device shared from a different Imou account by chance? Can you please share debug logs when opening the video stream? (https://github.com/user2684/imou_life?tab=readme-ov-file#debugging) thanks!

**Comment by Ices-Eyes** [comment]
Hi, I've installed the plugin and have this same camera. Perhaps, I see there is no human detection sensor for this camera, that is available from imou app... Any chancce it will be added, as long as with the support of the 2 channels? :)
