### ISSUE TITLE
Change Callback URL

### ISSUE THREAD

**Issue by array81** [user2684/imou_life#90]
I use imou_life with 3 camera. Now I need change the callback url. I try to reconfig and add the new URL but the old address always remains in the device properties.

**Comment by user2684** [comment]
The callback ulr is common across all the cameras of the account so ensure you change it only in one place. If you have any issue, try changing it from the developer console on https://open.imoulife.com/ as a workaround. Thanks

**Comment by user2684** [comment]
Ok, wonder if this is related to #14 / #29. The HTTP request sent from the Imou servers is malformed so the only way I could make it working with HA was to have a proxy in the middle. Try having a look at https://github.com/user2684/imou_life?tab=readme-ov-file#option-3 and specifically the reverse proxy configuration. Thanks
