### ISSUE TITLE
message erreur API distant imou life

### ISSUE THREAD

**Issue by nico261182** [user2684/imou_life#91]
bonjour 
je me permet de vous contacter car je suis entrain d ajouté mes camera sur mon home assistant via l application imou life .
j ai bien récupéré l ID et la clée secret  mais j ai un message d erreur d adresse  api distant non valide

voici l adresse marqué dans l application https://openapi.easy4ip.com/openapi

avez vous déjà eu ce souci merci

**Comment by user2684** [comment]
Hi, can you please there debugging logs as per https://github.com/user2684/imou_life?tab=readme-ov-file#troubleshooting ?
Thanks

**Comment by nico261182** [comment]
bonjour 
j ai finalement trouver mon probleme , j utilisais navigateur chrome quand je voulais mon appsecret et a ce moment quand on la copie , et qu on la colle dans l application c est mauvais , elle copie des etoile 
alors que si on utilise Edge et quand regarde l appsecret on a bien le code

**Comment by user2684** [comment]
Perfect, glad to solved the issue. Thanks
