### ISSUE TITLE
OP 1013 Call interface times exceed limit (total). What this is meaning? 

### ISSUE THREAD

**Issue by peppe-terra** [user2684/imou_life#94]
I now that there is a day limit calls for each API as explained here https://open.imoulife.com/book/faq/limit.html, but I don't know to what the message "OP 1013 Call interface times exceed limit (total)" is related. Any suggestion?
I get this message every time I use any entity provided by the integration.

**Comment by Paga777** [comment]
I think that now with the new rules you pay for practically every operation. I'm quite annoyed with this.
try going to the developers site in your account and check your balance. charge a dollar and you'll see that it works again
very sad thing

**Comment by peppe-terra** [comment]
I think you are right. 
![Imou](https://github.com/user2684/imou_life/assets/58150632/993d838a-6a9f-4652-9bff-e03e7c205a40)

I'm going to recharge and I will give a feedback.

**Comment by peppe-terra** [comment]
I reacharged my balance and everything is working fine. We must pay to use API. I think there are free calls for every account and after that you must pay. I think I finished my free calls since I use API to move programmatically my cameras using PTZ service.
Thank for reply.

**Comment by Paga777** [comment]
yes, I made $5 in 3 seconds just for streaming.
I use them in the home assistant for real time streaming and I deactivate and activate movement detection via automations so it has become unusable for me.
For now I will try the configuration via ONVIF and use additional motion sensors and sooner or later I will definitively abandon the imou ecosystem.

**Comment by peppe-terra** [comment]
I use ONVIF for streaming. I think $0.02 for 10,000 calls to API is not much expensive.  $0.25 / GB for streaming is too much according to me.

**Comment by user2684** [comment]
Yeah, looks like there is now a limit per API call and specifically:
①    Interface call times: There is a monthly free limit of 30,000 times, and the excess is charged at a unit price of $0.02/10,000 times;
②    Message push times: There is a monthly free quota of 30,000 times, and the excess is charged at a unit price of $0.01/10,000 times;
③    Media Flow: There is a free quota of 2GB per month, and overage is charged at a unit price of $0.25/GB. 
I still need to figure out how this would affect the operation of the integration. Definitely something to add to the documentation

**Comment by tapsystem** [comment]
Hi,
Do you have an idea of How can i intercept the error "OP 1013 Call interface times exceed limit (total)" in HA  ( in script or automation) to avoid the problem stoping loop or actions sequences ?
the "continue_on_error: true" don't look to be enough.
Thanks by advance

**Comment by peppe-terra** [comment]
Sorry I don't know. I intercepted the error using node red. I think that you can intercept it analyzing home assistant logs.

**Comment by tapsystem** [comment]
if you intercept the error with nodRed, can you continue executing the current script / batch ?

**Comment by peppe-terra** [comment]
Node red has a catch node that you can use the handle the error as you like. 

Il giorno 13 mag 2024, 22:20, alle ore 22:20, TapSystem ***@***.***> ha scritto:

**Comment by user2684** [comment]
Closing since due to API limit restrictions now documented in the wiki
