### ISSUE TITLE
Three cameras, only one showing preview

### ISSUE THREAD

**Issue by syntesys87** [user2684/imou_life#95]
Hello, 

I have three cameras, but only one is showing preview; the others does not work.

Using component version 1.0.15.

Here attached the debug log. What configuration file do you need?

Thank you.

[home-assistant_imou_life_2024-02-29T10-34-55.635Z.log](https://github.com/user2684/imou_life/files/14446702/home-assistant_imou_life_2024-02-29T10-34-55.635Z.log)

**Comment by user2684** [comment]
Hi, I see the error message "NotAuthorized: OP1009: No right, cannot operate" as if your credentials do not have permissions to operate the device. Is the device a shared device?

**Comment by syntesys87** [comment]
Hi,
Yes, it's a shared device, but in the app it works well.

**Comment by user2684** [comment]
Ok than is related to what we discussed in #88, looks like for some devices there is a different set of API for shared devices we have been not able to identified yet. Adding to the "blocked" queue unless this new api is found. Thanks

**Comment by syntesys87** [comment]
The question is: why with one camera it works? 
All the three cameras are shared...

**Comment by user2684** [comment]
First time I see this situation, usually users reported a all-or-nothing with shared devices. No idea, unfortunately unless Imou will update the documentation of the API, emulating what the app does is really hard (#63)

**Comment by user2684** [comment]
Added to https://github.com/user2684/imou_life/wiki/Known-Issues
