### ISSUE TITLE
Remote API Error during configuration

### ISSUE THREAD

**Issue by dgarimoldi** [user2684/imou_life#96]
Hello,
integration was working fine till some days ago, then stopped.
Tried to delete the configuration and create from scratch but now Iget the error: Remote API Error 

## Version of the custom_component

1.0.15

## Configuration
Configuration made via UI inserting AppID and APPSecret, before it worked, now it doeas not work anymore

Home Assistant
Core: 2024.2.5
Supervisor: 2024.02.1
Operating system: 12.0
Frontend: 20240207.1

Thanks for support

**Comment by thangnd85** [comment]
It's server side. Please wait sometimes then try to reload configuration.

**Comment by dgarimoldi** [comment]
Great thanks,  it works again now

Il Ven 1 Mar 2024, 08:57 thangnd85 ***@***.***> ha scritto:

**Comment by jose-cavalheri** [comment]
HI Team,
Even if lower than 30K per month is still failing during reload of configuration.
<img width="1194" alt="image" src="https://github.com/user2684/imou_life/assets/138793867/9bef6075-89f7-4fa0-a135-8b829d227a9b">

<img width="289" alt="image" src="https://github.com/user2684/imou_life/assets/138793867/d0cc6bc1-0b7d-401e-b3eb-0d21eed15017">

**Comment by thangnd85** [comment]
Add balance about 1$ into your account. It may help you.
------------------------------------------------------------
Thanks & Best regards
Thang, Nguyen Duc
Mobile: (+84) 985 435 685



Vào Th 2, 22 thg 4, 2024 vào lúc 22:33 Jose Cavalheri <
***@***.***> đã viết:

**Comment by crssba** [comment]
openapi.lechange.cn
api换成这个

**Comment by tobiradi** [comment]
I don't get any notifications about person detection. I can't activate the switch in HA either. There is the error: Error calling service switch/turn_off. 40999: Unknown error. The same with various other switches. What do I have to do for this to work? Does this have something to do with the API?

**Comment by jose-cavalheri** [comment]
Thanks @thangnd85 !!!

Indeed worked like a charm!!  Just 1 dolar it enabled back all the services!
<img width="419" alt="image" src="https://github.com/user2684/imou_life/assets/138793867/3c070db8-90c3-44ab-b0af-6167433a8927">


<img width="680" alt="image" src="https://github.com/user2684/imou_life/assets/138793867/f6f672b4-6475-4e83-831c-f9afaa476cec">
 
thanks for helping! Good TIP!

**Comment by user2684** [comment]
Just for your reference, I've summarized all the information regarding this on https://github.com/user2684/imou_life/wiki/Imou-API-usage-restrictions. Thanks
