### ISSUE TITLE
Stream not working anymore

### ISSUE THREAD

**Issue by QNTLO** [user2684/imou_life#98]
## Version of the custom_component

1.0.15

## Configuration
Configuration made via UI inserting AppID and APPSecret.

Home Assistant
Core: 2024.3.0
Supervisor: 2024.02.1
Operating system: 12.0
Frontend: 20240306.0

## Describe the bug

The stream doesn't work anymore. I have a card added in my dashboard, but it only shows a snapshot.
My scripts - that record a 10 sec video - don't work anymore. Through ffmpeg it works with an rtps stream, but I don't want to rely on that. I never run them simultaneous. I have already deleted the integration (restart) then installed it again (restart) but that doesn't solve anything. Also tried to delete the stream from my dashboard, but that was unfortunatly not the problem. 

When the script runs, it doesn't finish the recording. When trying to run it again, it shows this error: 
Stream already recording to /media/records/SnapVid.mp4!

## Debug log

```text

2024-03-09 13:29:29.487 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.voordeur_camera] Error from stream worker: Stream ended; no additional packets
2024-03-09 13:29:29.491 DEBUG (stream_worker) [homeassistant.components.stream.stream.camera.voordeur_camera] Restarting stream worker in 10 seconds: https://cmgw-online-fk.easy4ipcloud.com:8890/LCO/9G08FF0RAZF6974/0/0/20231119T154506/66e55122dfa106b42e13fdbf45bcff11.m3u8?proto=https
2024-03-09 13:29:40.223 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.voordeur_camera] Error from stream worker: Stream ended; no additional packets
2024-03-09 13:29:40.227 DEBUG (stream_worker) [homeassistant.components.stream.stream.camera.voordeur_camera] Restarting stream worker in 20 seconds: https://cmgw-online-fk.easy4ipcloud.com:8890/LCO/9G08FF0RAZF6974/0/0/20231119T154506/66e55122dfa106b42e13fdbf45bcff11.m3u8?proto=https
2024-03-09 13:30:00.965 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.voordeur_camera] Error from stream worker: Stream ended; no additional packets

```

**Comment by user2684** [comment]
Hi, I wonder if this is related to the new limits Imou put on the service (https://community.home-assistant.io/t/imou-life-cloud-integration/462439/202). Have a look at https://open.imoulife.com/consoleNew/resourceManage/myResource(the third bucket)  in case you have reached already the limit for video streaming. Thanks

**Comment by QNTLO** [comment]
Hi, 

Thanks for thinking with me. I already thought of that, since I received emails about it. 
But it wouldn't make sense, right? Since the limits are daily. So technically it should work at 00.01 since the timer resets again. 
And I don't make that many recordings. It only does when there is motion. To back up that claim, please see my limits for today (March 10th) at 20:30

![Schermafbeelding 2024-03-10 203113](https://github.com/user2684/imou_life/assets/60070328/761ffcf7-0e40-478c-bd31-f04c06cc3376)

**Comment by user2684** [comment]
Actually the email says limits are daily, at least this is what I'm experiencing here :-/

**Comment by QNTLO** [comment]
> Actually the email says limits are daily, at least this is what I'm experiencing here :-/

You mean monthly? 
Based on the screenshot i've send, I should still be able to use the stream, no?

I saw a screenshot at another thread, saying 'residue' at the flow as well, whereas with me it doesn't say so. Does that mean I'm at the limit already, or haven't used any yet. It is very confusing. 
I've just put $1 on my account, just to see what will happen next.

**Comment by user2684** [comment]
This is my understanding, if you don't see residue, it means you already reached the limit and you get API limit exceeded error messages in HA logs and you need to either wait for the next month or charge the account, at least this is what is happening to me

**Comment by user2684** [comment]
Ah, if you need the video stream, just use the ONVIF integration and there will be no limits there

**Comment by QNTLO** [comment]
Is the ONVIF better than the ffmpeg I've been using as an alternative? Pure quality wise?

**Comment by user2684** [comment]
Don't know, I expect onvif and ffmpeg to have similar quality, actually I think onvif uses ffmpeg behind the scene

**Comment by user2684** [comment]
Closing for now, feel free to reopen it if needed
